/**
 * NotesView — displays AI-generated study notes with download & print-to-PDF.
 */
export default function NotesView({ notes, topic }) {
  const handleDownload = () => {
    const a = document.createElement('a')
    a.href = URL.createObjectURL(new Blob([notes], { type: 'text/plain' }))
    a.download = `${topic.replace(/\s+/g, '-').toLowerCase()}-notes.txt`
    a.click()
  }

  const handlePrint = () => {
    const w = window.open('', '_blank')
    w.document.write(`
      <!doctype html>
      <html>
      <head>
        <title>${topic} — IKS Study Notes</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@400;600&family=Cinzel:wght@700&display=swap');
          body {
            font-family: 'Crimson Pro', serif;
            padding: 60px;
            max-width: 720px;
            margin: auto;
            background: #FEFCF7;
            color: #1A1205;
            line-height: 1.9;
          }
          h1 {
            font-family: 'Cinzel', serif;
            color: #C8520A;
            border-bottom: 2px solid #C8520A33;
            padding-bottom: 12px;
            margin-bottom: 32px;
            font-size: 28px;
          }
          .content {
            white-space: pre-wrap;
            font-family: inherit;
            font-size: 16px;
          }
          .footer {
            margin-top: 48px;
            padding-top: 12px;
            border-top: 1px solid #C8520A33;
            color: #9C814A;
            font-size: 12px;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <h1>ॐ ${topic} — Study Notes</h1>
        <div class="content">${notes}</div>
        <div class="footer">Generated by IKS Study Helper · Powered by Claude AI · ${new Date().toLocaleDateString()}</div>
      </body>
      </html>
    `)
    w.document.close()
    w.print()
  }

  return (
    <div style={{ animation: 'fadeUp 0.4s ease' }}>
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{
            width: 40, height: 40, borderRadius: 10,
            background: '#D4A01720',
            border: '1px solid #D4A01744',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 20,
          }}>📜</div>
          <div>
            <div style={{ fontFamily: "'Cinzel', serif", fontSize: 16, fontWeight: 600, color: '#F0C040' }}>
              Study Notes
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', fontFamily: "'JetBrains Mono', monospace" }}>
              {topic}
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 8 }}>
          {[['⬇', handleDownload, 'Download TXT'], ['🖨', handlePrint, 'Print / Save PDF']].map(([icon, fn, label]) => (
            <button key={label} onClick={fn} title={label} style={{
              width: 36, height: 36, borderRadius: 8,
              border: '1px solid var(--border)',
              background: 'transparent',
              color: 'var(--text-muted)',
              cursor: 'pointer', fontSize: 15,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              transition: 'border-color 0.2s, color 0.2s',
            }}
              onMouseEnter={e => { e.currentTarget.style.borderColor = '#D4A01766'; e.currentTarget.style.color = '#D4A017' }}
              onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.color = 'var(--text-muted)' }}
            >{icon}</button>
          ))}
        </div>
      </div>

      <div style={{
        background: 'var(--glass)',
        borderRadius: 14,
        padding: '28px 32px',
        border: '1px solid var(--border)',
        lineHeight: 2,
        fontFamily: "'Crimson Pro', serif",
        color: 'var(--text)',
        fontSize: 16,
        whiteSpace: 'pre-wrap',
        maxHeight: 520,
        overflowY: 'auto',
        letterSpacing: 0.3,
      }}>{notes}</div>
    </div>
  )
}
